[providers]
node = "18"

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y python3 python3-pip g++ gcc default-jdk",
    "update-alternatives --install /usr/bin/python python /usr/bin/python3 1"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node Api.js"